package com.zeroday.model

import kotlinx.serialization.Serializable
import java.util.UUID

@Serializable
data class Player(
    val id: String = UUID.randomUUID().toString(),
    val username: String,
    var passwordHash: String = "",
    var level: Int = 1,
    var experience: Long = 0,
    var experienceToNext: Long = 100,
    var cpu: Int = 100,
    var maxCpu: Int = 100,
    var ram: Int = 256,
    var maxRam: Int = 256,
    var bandwidth: Int = 50,
    var maxBandwidth: Int = 50,
    var credits: Long = 0,
    var reputation: Int = 0,
    var prestigeLevel: Int = 0,
    var prestigePoints: Long = 0,
    var unlockedCommands: MutableSet<String> = mutableSetOf("help", "scan", "connect", "whoami", "status"),
    var discoveredNodes: MutableSet<String> = mutableSetOf("localhost"),
    var activeTasks: MutableList<TaskInstance> = mutableListOf(),
    var completedTasks: MutableList<String> = mutableListOf(),
    var completedStorylines: MutableList<String> = mutableListOf(),
    var isBanned: Boolean = false,
    var banReason: String? = null,
    var currentStoryline: String? = null,
    var storylineProgress: Int = 0,
    var lastLoginIp: String = "127.0.0.1",
    var isOnline: Boolean = false,
    var partyId: String? = null,
    var factionId: String? = null,
    var inventory: MutableList<InventoryItem> = mutableListOf(),
    var activeZeroDayExploits: MutableList<InventoryItem> = mutableListOf(),
    var firewallBoost: Int = 0,
    var worldEventParticipation: MutableSet<String> = mutableSetOf(), // IDs of events player has joined
    var achievementProgress: MutableMap<String, AchievementProgress> = mutableMapOf(),
    var unlockedAchievements: MutableSet<String> = mutableSetOf(),
    var skillPoints: Int = 0,
    var unlockedSkills: MutableSet<String> = mutableSetOf(),
    var notifications: MutableList<Notification> = mutableListOf(),
    var lastChallengeRotation: Long = 0L,
    var activeChallenges: MutableList<ActiveChallenge> = mutableListOf(),
    /** Internal: 0 unless the player just levelled up; cleared after read. */
    var lastLevelNotified: Int = 0,
    /** Total credits ever earned (for lifetime achievements). */
    var lifetimeCreditsEarned: Long = 0L,

    // ---- Career System (v2.0) ----
    var careerPath: String = "undecided",         // "undecided", "whitehat", "blackhat"
    var heatLevel: Int = 0,
    var maxHeatLevel: Int = 100,
    var notoriety: Int = 0,
    var justicePoints: Int = 0,
    var bountyPrice: Long = 0,
    var timesArrested: Int = 0,
    var isInJail: Boolean = false,
    var jailTimeRemaining: Float = 0f,
    var whiteHatRank: Int = 0,
    var blackHatRank: Int = 0,
    var successfulHeists: Int = 0,
    var tracesCovered: Int = 0,

    // ---- Zone / World State ----
    var currentZoneId: String = "safehouse",
    var zoneControlContributions: MutableMap<String, Int> = mutableMapOf(),  // zoneId -> contribution
    var factionReputations: MutableMap<String, Int> = mutableMapOf(),       // factionId -> rep

    // ---- Login Streak / Activity ----
    var lastLoginAt: Long = 0L,
    var loginStreak: Int = 0,
    var longestStreak: Int = 0,
    var totalLogins: Int = 0,

    // ---- Equipment Degradation ----
    var equipmentDurability: MutableMap<String, Int> = mutableMapOf(),      // itemId -> durability
    var masteryGems: MutableList<String> = mutableListOf(),                 // gem item IDs

    // ---- Breakthrough ----
    var breakthroughLevels: MutableList<Int> = mutableListOf(),
    var breakthroughMultiplier: Double = 1.0
)

@Serializable
data class PlayerSnapshot(
    val id: String,
    val username: String,
    val level: Int,
    val experience: Long,
    val experienceToNext: Long,
    val cpu: Int,
    val maxCpu: Int,
    val ram: Int,
    val maxRam: Int,
    val bandwidth: Int,
    val maxBandwidth: Int,
    val credits: Long,
    val reputation: Int,
    val prestigeLevel: Int,
    val prestigePoints: Long,
    val unlockedCommands: Set<String>,
    val discoveredNodesCount: Int,
    val activeTasks: List<TaskInstance>,
    val completedTasksCount: Int,
    val currentStoryline: String?,
    val storylineProgress: Int,
    val factionId: String?,
    val inventory: List<InventoryItem>,
    val activeZeroDayExploits: Int,
    val firewallBoost: Int,
    val worldEventParticipation: Int,
    val unlockedAchievementCount: Int,
    val skillPoints: Int,
    val unlockedSkillCount: Int,
    val unreadNotifications: Int,
    val activeChallengeCount: Int,
    val careerPath: String,
    val heatLevel: Int,
    val notoriety: Int,
    val justicePoints: Int,
    val bountyPrice: Long,
    val currentZoneId: String,
    val breakthroughMultiplier: Double,
    val loginStreak: Int,
    val totalLogins: Int
)

fun Player.toSnapshot() = PlayerSnapshot(
    id = id,
    username = username,
    level = level,
    experience = experience,
    experienceToNext = experienceToNext,
    cpu = cpu,
    maxCpu = maxCpu,
    ram = ram,
    maxRam = maxRam,
    bandwidth = bandwidth,
    maxBandwidth = maxBandwidth,
    credits = credits,
    reputation = reputation,
    prestigeLevel = prestigeLevel,
    prestigePoints = prestigePoints,
    unlockedCommands = unlockedCommands.toSet(),
    discoveredNodesCount = discoveredNodes.size,
    activeTasks = activeTasks.toList(),
    completedTasksCount = completedTasks.size,
    currentStoryline = currentStoryline,
    storylineProgress = storylineProgress,
    factionId = factionId,
    inventory = inventory.toList(),
    activeZeroDayExploits = activeZeroDayExploits.size,
    firewallBoost = firewallBoost,
    worldEventParticipation = worldEventParticipation.size,
    unlockedAchievementCount = unlockedAchievements.size,
    skillPoints = skillPoints,
    unlockedSkillCount = unlockedSkills.size,
    unreadNotifications = notifications.count { !it.read },
    activeChallengeCount = activeChallenges.size,
    careerPath = careerPath,
    heatLevel = heatLevel,
    notoriety = notoriety,
    justicePoints = justicePoints,
    bountyPrice = bountyPrice,
    currentZoneId = currentZoneId,
    breakthroughMultiplier = breakthroughMultiplier,
    loginStreak = loginStreak,
    totalLogins = totalLogins
)

fun PlayerSnapshot.toMap(): Map<String, Any?> = mapOf(
    "id" to id,
    "username" to username,
    "level" to level,
    "experience" to experience,
    "experienceToNext" to experienceToNext,
    "cpu" to cpu,
    "maxCpu" to maxCpu,
    "ram" to ram,
    "maxRam" to maxRam,
    "bandwidth" to bandwidth,
    "maxBandwidth" to maxBandwidth,
    "credits" to credits,
    "reputation" to reputation,
    "prestigeLevel" to prestigeLevel,
    "prestigePoints" to prestigePoints,
    "unlockedCommands" to unlockedCommands.toList(),
    "discoveredNodesCount" to discoveredNodesCount,
    "activeTasks" to activeTasks.map { it.toMap() },
    "completedTasksCount" to completedTasksCount,
    "currentStoryline" to currentStoryline,
    "storylineProgress" to storylineProgress,
    "factionId" to factionId,
    "inventory" to inventory.map { it.toMap() },
    "activeZeroDayExploits" to activeZeroDayExploits,
    "firewallBoost" to firewallBoost,
    "worldEventParticipation" to worldEventParticipation,
    "unlockedAchievementCount" to unlockedAchievementCount,
    "skillPoints" to skillPoints,
    "unlockedSkillCount" to unlockedSkillCount,
    "unreadNotifications" to unreadNotifications,
    "activeChallengeCount" to activeChallengeCount,
    "careerPath" to careerPath,
    "heatLevel" to heatLevel,
    "notoriety" to notoriety,
    "justicePoints" to justicePoints,
    "bountyPrice" to bountyPrice,
    "currentZoneId" to currentZoneId,
    "breakthroughMultiplier" to breakthroughMultiplier,
    "loginStreak" to loginStreak,
    "totalLogins" to totalLogins
)
